config/routes.rb
Marcas::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create", :as => "login"

  get "signup" => "users#new", :as => "signup"
  get "edit_password/:id" => "users#edit_password", :as => "edit_password"
  put "edit_password/:id" => "users#update_password", :as => "update_password"

  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"

  get "index" => "home#index", :as => "home"
  get "trademark_registration" => "home#trademark_registration", :as => "trademark_registration"

  root :to => "home#index"

  resources :users do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :password_resets

  resources :trademark_orders
  resources :services
  resources :order_types
  resources :order_statuses
  
  get "orders/edit_status/:id" => "orders#edit_status", :as => "edit_status"
  put "orders/update_status/:id" => "orders#update_status", :as => "update_status"

  get "checkout/:id" => "cart#checkout", :as => "checkout"
  post "pay/:id" => "cart#pay", :as => "payment"
  match "order_confirmation" => "cart#order_confirmation"
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :order_type
  has_many :orders

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_length_of :name, :within => 3..50

  validates_presence_of :price
  validates_numericality_of :price

  validates_presence_of :order_type_id

  def self.find_by_order_type_name(name)
    joins(:order_type).where(:order_types => {name: name})
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def edit
    @service = Service.find(params[:id])
  end

  def create
    @service = Service.new(params[:service])

    if @service.save
      redirect_to @service, notice: t('services.flash.create.notice')
    else
      render :new
    end
  end

  def update
    @service = Service.find(params[:id])

    if @service.update_attributes(params[:service])
      redirect_to @service, notice: t('services.flash.update.notice')
    else
      render :edit
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    redirect_to services_url
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for @service, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @service.errors.any? %>
    <div id="error" class="alert alert-error">
      <% for message in @service.errors.full_messages %>
      <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend><%= t('services.form.title') %></legend>
    
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :price, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :price, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :order_type, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select :order_type_id, OrderType.all, :id, :name %>
      </div>
    </div>
    
    <div class="form-actions">
      <%= f.submit button_label, :class => 'btn btn-primary', :id => 'commit' %>
      <%= link_to t('buttons.cancel'), services_path, :class => 'btn'  %>
    </div>
  </fieldset>
<% end %>

app/views/services/index.html.erb
<p>
  <h1><%= t('services.index.title') %></h1>
</p>

<% if @services.empty? %>
  <div class="alert alert-info">
    <%= t('services.index.empty') %>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('helpers.label.service.id') %></th>
        <th><%= t('helpers.label.service.name') %></th>
        <th><%= t('helpers.label.service.price') %></th>
        <th><%= t('helpers.label.service.order_type') %></th>
        <th><%= t('actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.id %></td>
          <td><%= link_to service.name, service_path(service) %></td>
          <td><%= number_to_currency(service.price) %></td>
          <td><%= service.order_type.name %></td>
          <td>
            <%= link_to t('buttons.edit'), edit_service_path(service), :class => 'btn btn-mini', :id => "edit-#{service.name.parameterize}" %>
            <%= link_to t('buttons.destroy'), service_path(service), confirm: t('messages.confirmation'), :class => 'btn btn-mini btn-danger', method: :delete, :id => "destroy-#{service.name.parameterize}" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to t('buttons.new'), new_service_path, :class => 'btn btn-primary', :id => 'new' %>

app/views/services/show.html.erb
<p>
  <h1><%= t('services.index.title') %></h1>
</p>

<p>
  <b><%= t('helpers.label.service.name') %></b><br />
  <%= @service.name %>
</p>

<p>
  <b><%= t('helpers.label.service.description') %></b><br />
  <%= @service.description %>
</p>

<p>
  <b><%= t('helpers.label.service.price') %></b><br />
  <%= number_to_currency(@service.price) %>
</p>

<p>
  <b><%= t('helpers.label.service.order_type') %></b><br />
  <%= @service.order_type.name %>
</p>

<div class="form-actions">
  <%= link_to t('buttons.back'), services_path, :class => 'btn'  %>
  <%= link_to t('buttons.edit'), edit_service_path(@service), :class => 'btn' %>
  <%= link_to t('buttons.destroy'), service_path(@service), :method => 'delete', :confirm => t('messages.confirmation'), :class => 'btn btn-danger' %>
</div>