config/routes.rb
Marcas::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create", :as => "login"

  get "signup" => "users#new", :as => "signup"
  get "edit_password/:id" => "users#edit_password", :as => "edit_password"
  put "edit_password/:id" => "users#update_password", :as => "update_password"

  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"

  get "index" => "home#index", :as => "home"
  get "trademark_registration" => "home#trademark_registration", :as => "trademark_registration"

  root :to => "home#index"

  resources :users do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :password_resets

  resources :trademark_orders
  resources :services
  resources :order_types
  resources :order_statuses
  
  get "orders/edit_status/:id" => "orders#edit_status", :as => "edit_status"
  put "orders/update_status/:id" => "orders#update_status", :as => "update_status"

  get "checkout/:id" => "cart#checkout", :as => "checkout"
  post "pay/:id" => "cart#pay", :as => "payment"
  match "order_confirmation" => "cart#order_confirmation"
end

app/controllers/order_statuses_controller.rb
class OrderStatusesController < ApplicationController
  before_filter :require_login
  load_and_authorize_resource

  def index
    @order_statuses = OrderStatus.all
  end

  def show
    @order_status = OrderStatus.find(params[:id])
  end

  def new
    @order_status = OrderStatus.new
  end

  def edit
    @order_status = OrderStatus.find(params[:id])
  end

  def create
    @order_status = OrderStatus.new(params[:order_status])
    
    handle_status

    if @order_status.save
      redirect_to @order_status, notice: t('order_statuses.flash.create.notice')
    else
        render :new
    end
  end

  def update
    @order_status = OrderStatus.find(params[:id])

    handle_status

    if @order_status.update_attributes(params[:order_status])
        redirect_to @order_status, notice: t('order_statuses.flash.update.notice')
    else
      render :edit
    end
  end

  def destroy
    @order_status = OrderStatus.find(params[:id])
    @order_status.destroy

    redirect_to order_statuses_url
  end

  private

  def handle_status
    if new_first_status
      remove_current_first_status
    end
  end

  def remove_current_first_status
    OrderStatus.remove_first_flag 
  end

  def new_first_status
    params[:order_status]["first_status"] == "1"
  end
end

app/helpers/order_statuses_helper.rb
module OrderStatusesHelper
  def options_for_color
    [[t('order_statuses.form.color.danger'), "progress-danger"], [t('order_statuses.form.color.warning'), "progress-warning"], [t('order_statuses.form.color.info'), "progress-info"], [t('order_statuses.form.color.success'), "progress-success"]]
  end

  def options_for_lifecycle
    OrderStatus::LIFECYCLES.collect do |e|
      [t("order_statuses.form.lifecycle.#{e[0]}"), e[1]]
    end
  end

  def progress_bar_from(color)
    raw <<-eos
      <div class="progress #{color}" style="width: 50px;">
        <div class="bar" style="width:100%;"></div>
      </div>
    eos
  end
end

app/views/order_statuses/_form.html.erb
<%= form_for @order_status, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @order_status.errors.any? %>
    <div id="error" class="alert alert-error">
        <% for message in @order_status.errors.full_messages %>
          <div><%= message %></div>
        <% end %>
    </div>
  <% end %>
  <fieldset>
    <legend><%= t('order_statuses.form.title') %></legend>

    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :status, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :color, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :color, options_for_color, { :include_blank => true }, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :lifecycle, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :lifecycle, options_for_lifecycle, :include_blank => true %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit button_label, :class => 'btn btn-primary', :id => "commit" %>
      <%= link_to t('buttons.cancel'), order_statuses_path, :class => 'btn'  %>
    </div>
  </fieldset>
<% end %>

app/views/order_statuses/edit.html.erb
<%= render :partial => 'form', :locals => { :button_label => t('buttons.update') } %>

app/views/order_statuses/index.html.erb
<p>
  <h1><%= t('order_statuses.index.title') %></h1>
</p>
<% if @order_statuses.empty? %>
  <div class="alert alert-info">
    <%= t('order_statuses.index.empty') %>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('helpers.label.order_status.id') %></th>
        <th><%= t('helpers.label.order_status.status') %></th>
        <th><%= t('helpers.label.order_status.lifecycle') %></th>
        <th><%= t('helpers.label.order_status.color') %></th>
        <th><%= t('actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @order_statuses.each do |order_status| %>
        <tr>
          <td><%= order_status.id %></td>
          <td><%= link_to order_status.status, order_status_path(order_status) %></td>
          <td><%= t("order_statuses.form.lifecycle.#{order_status.lifecycle}") %></td>
          <td><%= progress_bar_from(order_status.color) %></td>
          <td>
            <%= link_to t('buttons.edit'), edit_order_status_path(order_status), :class => 'btn btn-mini', :id => "edit-#{order_status.status.parameterize}" %>
            <%= link_to t('buttons.destroy'), order_status_path(order_status), :method => :delete, :confirm => t('messages.confirmation'), :class => 'btn btn-mini btn-danger', :id => "destroy-#{order_status.status.parameterize}"  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to t('buttons.new'), new_order_status_path, :class => 'btn btn-primary', :id => "new" %>

app/views/order_statuses/show.html.erb
<p>
  <h1><%= t('order_statuses.show.title') %></h1>
</p>

<p>
  <b><%= t('helpers.label.order_status.status') %></b><br>
  <%= @order_status.status %>
</p>

<p>
  <b><%= t('helpers.label.order_status.description') %></b><br>
  <%= @order_status.description %>
</p>

<p>
  <b><%= t('helpers.label.order_status.lifecycle') %></b><br />
  <%= t("order_statuses.form.lifecycle.#{@order_status.lifecycle}") %>
</p>

<p>
  <b><%= t('helpers.label.order_status.color') %></b>
  <%= progress_bar_from(@order_status.color) %>
</p>

<div class="form-actions">
  <%= link_to t('buttons.back'), order_statuses_path, :class => 'btn'  %>
  <%= link_to t('buttons.edit'), edit_order_status_path(@order_status), :class => 'btn' %>
  <%= link_to t('buttons.destroy'), order_status_path(@order_status), :method => 'delete', :confirm => t('messages.confirmation'), :class => 'btn btn-danger' %>
</div>