config/routes.rb
Marcas::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create", :as => "login"

  get "signup" => "users#new", :as => "signup"
  get "edit_password/:id" => "users#edit_password", :as => "edit_password"
  put "edit_password/:id" => "users#update_password", :as => "update_password"

  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"

  get "index" => "home#index", :as => "home"
  get "trademark_registration" => "home#trademark_registration", :as => "trademark_registration"

  root :to => "home#index"

  resources :users do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :password_resets

  resources :trademark_orders
  resources :services
  resources :order_types
  resources :order_statuses
  
  get "orders/edit_status/:id" => "orders#edit_status", :as => "edit_status"
  put "orders/update_status/:id" => "orders#update_status", :as => "update_status"

  get "checkout/:id" => "cart#checkout", :as => "checkout"
  post "pay/:id" => "cart#pay", :as => "payment"
  match "order_confirmation" => "cart#order_confirmation"
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :orders

  attr_accessible :username, :email, :password, :password_confirmation

  validates_confirmation_of :password

  validates_presence_of :username, :password, :email

  validates_length_of :username, :within => 3..20
  validates_length_of :password, :within => 6..30

  validates_uniqueness_of :username, :email

  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i

  def self.all_customers
    where("role = ?", "customer")
  end
  
  def admin?
    role == "admin"
  end

  def customer?
    role == "customer"
  end

  def active?
    activation_state == "active"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :except => [:new, :create, :activate]
  load_and_authorize_resource :except => [:new, :create, :activate]

  include SslRequirement
  ssl_exceptions

  attr_writer :user

  def index
    @users = User.all_customers
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def edit_password
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    @user.role = :customer

    if @user.save
      redirect_to root_url, notice: t('users.flash.create.notice')
    else
      render :new
    end
  end

  def update
    render :edit
  end

  def update_password
    if change_password(params[:user])
      redirect_to root_url, notice: t('users.flash.update_password.notice')
    else
      render :edit_password
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url, notice: t('users.flash.destroy.notice')
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to login_path, :notice => t('users.flash.activate.notice')
    else
      not_authenticated
    end
  end

  private

  def change_password(attributes)
    unless login(@user.username, attributes["old_password"])
      @user.errors.add(:old_password, t('activerecord.errors.messages.invalid'))
      return false
    end
    @user.password = attributes["password"]
    @user.password_confirmation = attributes["password_confirmation"]
    @user.save! if @user.valid?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def formatted_activation_status_for(user)
    if user.active? 
      raw "<span class=\"label label-success\">#{t('users.index.active')}</span>"
    else
      raw "<span class=\"label label-warning\">#{t('users.index.unactive')}</span>"
    end 
  end
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
        <% for message in @user.errors.full_messages %>
          <div><%= message %></div>
        <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend><%= controller.action_name.capitalize %> User</legend>

    <div class="control-group">
      <%= f.label :username, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :username, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <% if controller.action_name == "edit" || controller.action_name == "update" %>
      <div class="control-group">
        <%= f.label :old_password, :class => 'control-label' %>
        <div class="controls">
          <%= f.password_field :old_password, :class => 'text_field' %>
        </div>
      </div>
    <% end %>

    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', root_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit_password.html.erb
<%= form_for @user, :url => update_password_path(@user), :method => :put, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @user.errors.any? %>
    <div id="error" class="alert alert-error">
        <% for message in @user.errors.full_messages %>
          <div><%= message %></div>
        <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend><%= t('users.edit_password.title') %></legend>

    <div class="control-group">
      <%= f.label :old_password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :old_password, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit t('users.edit_password.buttons.change_password'), :id => "commit", :class => 'btn btn-primary' %>
      <%= link_to t('buttons.cancel'), root_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/users/index.html.erb
<p>
  <h1><%= t('users.index.title') %></h1>
</p>
<% if @users.empty? %>
  <div class="alert alert-info">
    <%= t('users.index.empty') %>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('helpers.label.user.id') %></th>
        <th><%= t('helpers.label.user.username') %></th>
        <th><%= t('helpers.label.user.email') %></th>
        <th><%= t('helpers.label.user.activation_state') %></th>
        <th><%= t('actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= link_to user.username, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= formatted_activation_status_for(user) %></td>
          <td>
            <%= link_to t('buttons.destroy'), user_path(user), :method => :delete, :confirm => t('messages.confirmation'), :class => 'btn btn-mini btn-danger', :id => "destroy-#{user.username}" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @user.errors.any? %>
    <div id="error" class="alert alert-error">
        <% for message in @user.errors.full_messages %>
          <div><%= message %></div>
        <% end %>
    </div>
  <% end %>

  <fieldset>
    <legend><%= t('users.new.title') %></legend>

    <div class="control-group">
      <%= f.label :username, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :username, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit t('users.new.buttons.register_user'), :class => 'btn btn-primary', :id => "commit" %>
      <%= link_to t('buttons.cancel'), root_path, :id => 'cancel', :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/users/show.html.erb
<p>
  <h1><%= t('users.show.title') %></h1>
</p>

<p>
  <b><%= t('helpers.label.user.username') %></b><br>
  <%= @user.username %>
</p>

<p>
  <b><%= t('helpers.label.user.email') %></b><br>
  <%= @user.email %>
</p>

<div class="form-actions">
  <% if can? :edit_password, @user %>
    <%= link_to t('users.edit_password.buttons.change_password'), edit_password_path(@user), :id => "change_password", :class => 'btn'  %>
  <% end %>
  <% if current_user.admin? %>
    <%= link_to t('buttons.back'), users_path, :class => 'btn'  %>
  <% else %>
    <%= link_to t('buttons.back'), root_path, :class => 'btn'  %>
  <% end %>
</div>