config/routes.rb
Marcas::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create", :as => "login"

  get "signup" => "users#new", :as => "signup"
  get "edit_password/:id" => "users#edit_password", :as => "edit_password"
  put "edit_password/:id" => "users#update_password", :as => "update_password"

  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"

  get "index" => "home#index", :as => "home"
  get "trademark_registration" => "home#trademark_registration", :as => "trademark_registration"

  root :to => "home#index"

  resources :users do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :password_resets

  resources :trademark_orders
  resources :services
  resources :order_types
  resources :order_statuses
  
  get "orders/edit_status/:id" => "orders#edit_status", :as => "edit_status"
  put "orders/update_status/:id" => "orders#update_status", :as => "update_status"

  get "checkout/:id" => "cart#checkout", :as => "checkout"
  post "pay/:id" => "cart#pay", :as => "payment"
  match "order_confirmation" => "cart#order_confirmation"
end

app/views/layouts/admin.html.erb
<% content_for :navbar_menu do %>
  <ul class="nav">
    <li><%= link_to t('trademark_orders.index.title'), trademark_orders_path, :id => 'trademark_orders' %></li>
    <li><%= link_to t('services.index.title'), services_path, :id => 'services' %></li>
    <li><%= link_to t('order_statuses.index.title'), order_statuses_path, :id => 'order_statuses' %></li>
    <li><%= link_to t('order_types.index.title'), order_types_path, :id => 'order_types' %></li>
    <li><%= link_to t('users.index.title'), users_path %></li>
  </ul>
<% end %>
<%= render :template => 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Marcas</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to t(:brand_name), root_url, class: "brand" %>
          <div class="container-fluid nav-collapse">
            <%= yield :navbar_menu %>
            <p class="navbar-text pull-right">
            <% if logged_in? %>
              <%= t('sessions.new.logged_as') %> <%= link_to current_user.username, user_path(current_user), :id => "my_account" %>.
              <%= link_to t('sessions.new.logout'), logout_path, :id => "logout" %>
            <% else %>
              <%= t(:make) %> 
              <%= link_to t('sessions.new.signup'), signup_path, :id => "signup" %> 
              <%= t(:or) %> 
              <%= link_to t('sessions.new.login'), login_path, :id => "login"%>.
            <% end %>
            </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <% if flash[:alert] %>
            <div id="error" class="alert alert-error">
              <%= flash[:alert] %>
            </div>
          <% elsif flash[:notice] %>
            <div class="alert alert-success">
              <%= flash[:notice] %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div><!--/row-->
  </div> <!-- /container -->

  <!-- Le javascript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/customer.html.erb
<% content_for :navbar_menu do %>
  <ul class="nav">
    <li><%= link_to t('trademark_orders.index.my_orders'), trademark_orders_path, :id => 'trademark_orders' %></li>
    <li><%= link_to t('services.trademarks.title'), trademark_registration_path, :id => 'trademark_registration' %></li>
  </ul>
<% end %>
<%= render :template => 'layouts/application' %>

app/views/layouts/guest.html.erb
<% content_for :navbar_menu do %>
  <ul class="nav">
    <li><%= link_to t('services.trademarks.title'), trademark_registration_path, :id => 'trademark_registration' %></li>
  </ul>
<% end %>
<%= render :template => 'layouts/application' %>